Add "Purple Dark" theme
giscus/giscus pull request #1144
Opened 2023-08-10 17:22 UTC by MystieHum

2023-08-12 15:17 UTC, laymonage requested changes

2023-08-12 15:17 UTC, laymonage commented on styles/themes/purpledark.css
> +  --color-accent-fg: rgba(var(--primary-default), 0.85);
Thank you, but this doesn't have enough colour contrast to pass accessibility checks:

<img width="297" alt="colour contrast of 2.84" src="https://github.com/giscus/giscus/assets/6379424/a1b06422-36f4-4706-9aae-372795cb4742">

<img width="352" alt="image" src="https://github.com/giscus/giscus/assets/6379424/f7d6b3c8-a3ea-4e4b-a618-df0b8d788cb9">


Could you use a different colour?

2023-08-12 16:29 UTC, MystieHum commented on styles/themes/purpledark.css
> +  --color-accent-fg: rgba(var(--primary-default), 0.85);
will look into that, thanks (didn't try with `a` and `code` tags)

2023-08-12 16:34 UTC, MystieHum commented on styles/themes/purpledark.css
> +  --color-accent-fg: rgba(var(--primary-default), 0.85);
by the way, how to solve this CORS error? is it even related to giscus or am i doing something wrong? i try to use my theme like that:
```
data-theme="https://realvanyek.eu.org/css/giscus.css"
```
but it gives this error and my theme doesn't load:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://realvanyek.eu.org/css/giscus.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

2023-08-12 16:55 UTC, laymonage commented on styles/themes/purpledark.css
> +  --color-accent-fg: rgba(var(--primary-default), 0.85);
You need to put a CORS header (`Access-Control-Allow-Origin`) to the response when hosting the CSS file on your website. How to do it depends on how your website is configured and hosted, but the goal is to make it so that when the browser requests the CSS file, the response includes the `Access-Control-Allow-Origin` header with a value that allows https://giscus.app (either explicitly or by wildcard `*`).

Example:
<img width="375" alt="image" src="https://github.com/giscus/giscus/assets/6379424/cc5be4e0-3e1d-4d83-95ad-c394942d5869">

I think Vercel automatically adds `Access-Control-Allow-Origin: *` to static files. For Netlify, you'll have to specify it manually: https://docs.netlify.com/routing/headers/

If it's hosted on a server using Nginx, you need to update your Nginx config e.g. https://enable-cors.org/server_nginx.html (be careful to only allow CORS for paths that you explicitly want to be accessed from other websites though)

2023-08-13 18:33 UTC, MystieHum commented
@laymonage does this look good now?

2023-08-19 17:44 UTC, laymonage approved these changes
Thanks @MystieHum, the new colour still didn't pass accessibility checks but I found a close enough colour that does – I had to use a hardcoded RGB value though. I've made a few other small tweaks and renamed the file from `purpledark.css` to `purple_dark.css` to better match the other themes. Thanks again!

2023-08-19 17:45 UTC, merged

2023-08-20 09:57 UTC, MystieHum commented
@laymonage no problem!

2023-08-20 10:03 UTC, devcat86 commented
cool theme :)