Add NoBorder Gray theme
giscus/giscus pull request #1203
Opened 2023-10-19 13:05 UTC by MystieHum

hello! i made another theme, this time a slightly different variant of NoBorder Dark

2023-10-26 06:06 UTC, MystieHum commented
@laymonage

2023-10-28 23:35 UTC, laymonage requested changes
Thanks, but there isn't enough contrast for links. Could you please fix it?

<img width="916" alt="image" src="https://github.com/giscus/giscus/assets/6379424/71359d2e-a93e-4b3d-aecb-d83d962c8f8b">

<img width="817" alt="image" src="https://github.com/giscus/giscus/assets/6379424/781e73ba-2017-4701-bebe-7842b596ba39">

2023-10-29 10:25 UTC, MystieHum commented
@laymonage i think that's enough contrast now
<img src="https://tinypic.host/images/2023/10/29/Screenshot_20231029_132244.png" width="600">

2023-10-29 19:19 UTC, laymonage approved these changes

2023-10-29 19:19 UTC, laymonage commented on styles/themes/noborder_gray.css
> +  --color-neutral-muted: rgb(175 184 193 / 20%);
I changed these into `19%` for a better contrast ratio, hope that's OK!

2023-10-29 19:22 UTC, merged

2023-10-30 07:40 UTC, MystieHum commented on styles/themes/noborder_gray.css
> +  --color-neutral-muted: rgb(175 184 193 / 20%);
that's ok!